### ISSUE TITLE
Upgrade to Keycloak 10

### ISSUE THREAD

**Issue by nikhiljha** [ocf/keycloak#3]
We're 4 major versions out of date 😱

https://www.keycloak.org/docs/latest/release_notes/

I haven't looked at the changes because there are a lot, but we should probably start thinking about upgrading or it's not going to be fun to do it eventually.

**Comment by jvperrin** [comment]
Agreed, upgrading would be great to do. They do also seem pretty liberal with their major versions though (that or they're moving quickly), as we're only on a version that's about a year old at this point (from April 2019), so that should help a bit.

**Comment by BernardZhao** [comment]
Can we upgrade straight away or would that break things

**Comment by nikhiljha** [comment]
Only one way to find out!

**Comment by ja5087** [comment]
https://www.keycloak.org/2019/04/versioning.html 
Interesting read on why the major version is changing so fast.

**Comment by ja5087** [comment]
Looks like it came up fine, if anyone spots any issues we can rollback

**Comment by nikhiljha** [comment]
@ja5087 Grafana says `Login provider denied login request`

Maybe don't rollback though, `kubectl logs` shows the error as `errorDesc="Invalid scopes: user:email"`, so it could be a small configuration fix.

**Comment by gruppferi** [comment]
@nikhiljha  did you find where was the problem with Grafana? I face the same issue with keycloak 11.0.3

    auth.generic_oauth:
      enabled: true
      client_id: grafana
      client_secret: xxxxxxxxxxxxx
      auth_url: {{ keycloak.publicUrl }}/auth/realms/xxxxxxx/protocol/openid-connect/auth
      token_url: {{ keycloak.publicUrl }}/auth/realms/xxxxxxxx/protocol/openid-connect/token
      api_url: {{ keycloak.publicUrl }}/auth/realms/xxxxxxxx/protocol/openid-connect/userinfo
      allow_sign_up: true

**Comment by ja5087** [comment]
I think we theorized that the `user:email` scope may have been renamed or similar in Keycloak. In our case this commit fixed it:

https://github.com/ocf/grafana/commit/ee92d145742a9006c5cdecdab94db8baf7ae9ab8

**Comment by gruppferi** [comment]
@ja5087 
I tried that one as well no luck, seems something else is also changed
      scope: openid profile email roles
      role_attribute_path: contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'
